# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodMinCnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('SH', 'SH'), ('SZ', 'SZ'), ('ALL', 'ALL')], default='SH', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField()),
                ('test', models.BooleanField(default=False)),
                ('min_cnt', models.IntegerField(blank=True, null=True)),
                ('market_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
