# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0002_periodmincnt_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeAnalyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('SH', 'SH'), ('SZ', 'SZ'), ('ALL', 'ALL')], default='SH', max_length=10)),
                ('start_period_start', models.DateField()),
                ('start_period_end', models.DateField(blank=True, null=True)),
                ('end_period_start', models.DateField()),
                ('end_period_end', models.DateField(blank=True, null=True)),
                ('test', models.BooleanField(default=False)),
                ('codes', models.TextField(blank=True, null=True)),
                ('cnts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
