# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0003_rangeanalyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeanalyse',
            name='decline',
            field=models.BooleanField(default=True),
        ),
    ]
