# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0006_auto_20180923_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDateAnalyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cnt', models.IntegerField()),
            ],
        ),
    ]
