# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0007_marketdateanalyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdateanalyse',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
