# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0008_marketdateanalyse_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdateanalyse',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='marketdateanalyse',
            name='date_type',
            field=models.CharField(choices=[('Y', 'year'), ('M', 'month')], default='Y', max_length=10),
        ),
    ]
