# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0010_auto_20180924_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdateanalyse',
            name='sum_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
