# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-25 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0011_auto_20180924_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmincnt',
            name='start_market_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='期初股票总数'),
        ),
        migrations.AlterField(
            model_name='periodmincnt',
            name='end_market_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='期末股票总数'),
        ),
    ]
