# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-06 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0012_auto_20180925_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liquidity', models.FloatField(blank=True, null=True)),
                ('shares', models.FloatField(blank=True, null=True)),
                ('is_min', models.FloatField(blank=True, null=True)),
                ('is_max', models.FloatField(blank=True, null=True)),
                ('close_liquidity_amount', models.FloatField(blank=True, null=True)),
                ('close_shares_amount', models.FloatField(blank=True, null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('market_size', models.FloatField(blank=True, null=True)),
                ('avg_close', models.FloatField(blank=True, null=True)),
                ('avg_high', models.FloatField(blank=True, null=True)),
                ('avg_low', models.FloatField(blank=True, null=True)),
                ('up_profit', models.FloatField(blank=True, null=True)),
                ('min_liquidity_profit', models.FloatField(blank=True, null=True)),
                ('min_shares_profit', models.FloatField(blank=True, null=True)),
                ('max_liquidity_profit', models.FloatField(blank=True, null=True)),
                ('max_shares_profit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='periodmincnt',
            name='min_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='破新低股票数'),
        ),
        migrations.AlterField(
            model_name='periodmincnt',
            name='period_end',
            field=models.DateField(verbose_name='期间末'),
        ),
    ]
