# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-07 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0015_auto_20181006_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmincnt',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
