# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-07 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0016_periodmincnt_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmincnt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
