# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-07 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0017_periodmincnt_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodMinCnt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('SH', 'SH'), ('SZ', 'SZ'), ('ALL', 'ALL')], default='ALL', max_length=10)),
                ('min_period_start', models.DateField(blank=True, null=True, verbose_name='计算新低起始日期')),
                ('min_period_end', models.DateField(verbose_name='计算新低截止日期')),
                ('period_end', models.DateField(verbose_name='截止日期')),
                ('test', models.BooleanField(default=False)),
                ('min_cnt', models.IntegerField(blank=True, null=True, verbose_name='破新低股票数')),
                ('market_size', models.IntegerField(blank=True, null=True)),
                ('codes', models.TextField(blank=True, null=True)),
                ('end_market_size', models.IntegerField(blank=True, null=True, verbose_name='期末股票总数')),
                ('start_market_size', models.IntegerField(blank=True, null=True, verbose_name='期初股票总数')),
                ('market_shares_amount', models.FloatField(blank=True, null=True)),
                ('market_liquidity_amount', models.FloatField(blank=True, null=True)),
                ('min_shares_amount', models.FloatField(blank=True, null=True)),
                ('min_liquidity_amount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='is_min',
            field=models.FloatField(blank=True, null=True, verbose_name='破新低股票数'),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='market_size',
            field=models.FloatField(blank=True, null=True, verbose_name='股票数'),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='min_liquidity_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='新低流通市值比例'),
        ),
        migrations.AlterField(
            model_name='marketinfo',
            name='min_shares_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='新低总市值比例'),
        ),
        migrations.AlterField(
            model_name='periodmincnt',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='期间初'),
        ),
    ]
