# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0018_auto_20181007_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmincnt2',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='periodmincnt2',
            name='min_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='计算新低截止日期'),
        ),
    ]
