# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0019_auto_20181008_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmincnt2',
            name='point_flag',
            field=models.BooleanField(default=False, verbose_name='计算定点'),
        ),
    ]
