# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0020_periodmincnt2_point_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChgDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall', models.BooleanField()),
                ('fall_range_start', models.FloatField()),
                ('fall_range_end', models.FloatField()),
                ('codes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChgSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='跌幅计算开始日期')),
                ('end', models.DateField(blank=True, null=True, verbose_name='跌幅计算截止日期')),
                ('step', models.FloatField(default=1.0, verbose_name='倍数步幅')),
            ],
        ),
        migrations.AddField(
            model_name='chgdetail',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datareader.ChgSetup'),
        ),
    ]
