# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20170922_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
