# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_value_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
