# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_value_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
