# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_report_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['report', 'seq']},
        ),
    ]
