# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='minus',
            field=models.ManyToManyField(blank=True, related_name='minus', to='report.Item'),
        ),
    ]
