# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20170925_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='seq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
