# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('outstanding', models.FloatField(blank=True, null=True)),
                ('totals', models.FloatField(blank=True, null=True)),
                ('totalassets', models.FloatField(blank=True, db_column='totalAssets', null=True)),
                ('liquidassets', models.FloatField(blank=True, db_column='liquidAssets', null=True)),
                ('fixedassets', models.FloatField(blank=True, db_column='fixedAssets', null=True)),
                ('reserved', models.FloatField(blank=True, null=True)),
                ('reservedpershare', models.FloatField(blank=True, db_column='reservedPerShare', null=True)),
                ('esp', models.FloatField(blank=True, null=True)),
                ('bvps', models.FloatField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('timetomarket', models.BigIntegerField(blank=True, db_column='timeToMarket', null=True)),
                ('undp', models.FloatField(blank=True, null=True)),
                ('perundp', models.FloatField(blank=True, null=True)),
                ('rev', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('gpr', models.FloatField(blank=True, null=True)),
                ('npr', models.FloatField(blank=True, null=True)),
                ('holders', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ts_stocks',
                'managed': False,
            },
        ),
    ]
