# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stocks', models.ManyToManyField(to='stock.Stock')),
            ],
        ),
    ]
