# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_value_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('manual', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['item__report', '-period', 'seq']},
        ),
        migrations.AlterField(
            model_name='item',
            name='report',
            field=models.CharField(choices=[('xjllb', '现金流量表'), ('zcfzb', '资产负债表'), ('lrb', '利润表'), ('formula', '计算值')], max_length=100),
        ),
        migrations.AddField(
            model_name='formula',
            name='adds',
            field=models.ManyToManyField(blank=True, related_name='adds', to='stock.Item'),
        ),
        migrations.AddField(
            model_name='formula',
            name='minus',
            field=models.ManyToManyField(blank=True, related_name='minus', to='stock.Item'),
        ),
    ]
